Рефакторинг сервера и добавление новых сущностей
fenixD3/WebServ pull request #1
Opened 2022-04-09 13:57 UTC by fenixD3

Обложил все комментами по предварительной коммункации компонентов. Пока не совсем доразобрался, сколько может быть физических серверов и как они матчатся с виртуальными

2022-04-09 14:51 UTC, splinehip requested changes
Надо заменить в коде вызовы std::cout и std::cerr на log.write(level из enum, fmt_msg, ...)

2022-04-09 14:51 UTC, splinehip commented on includes/Server.h
> +#define DEF_PORT "666"
Дефолтный порт лучше делать выше 1000, например 8080. Не помню точно, но на линуксе вроде на портах меньше 1000 сидят системные сервисы и нужны права дополнительные. Могу ошибаться.

2022-04-10 08:06 UTC, fenixD3 commented on includes/Server.h
> +#define DEF_PORT "666"
Два разных коммента в одном топике - не оч удобно отвечать)

1. Про замену на логер - это не актуально для текущего PR, потому что самого логера здесь нет. Обычно, кто последним в мастер вмерживает - тот и исправляет такие вещи
2. Да, верно до 1024 порта зарезервировано, не факт, что там что-то крутится. Но имея sudo можно использовать и ниже порты. Но со сменой идея ок

2022-04-10 08:37 UTC, splinehip approved these changes

2022-04-10 08:38 UTC, merged