cgi alpha
fenixD3/WebServ pull request #14
Opened 2022-05-26 20:20 UTC by sdshorin

2022-05-27 05:23 UTC, fenixD3 requested changes

2022-05-27 05:23 UTC, fenixD3 commented on srcs/CgiWorker.cpp
> +	return ReadFile("./tmp/webserv_cgi");
Здесь же путь должен быть из конфига по идее?

2022-05-27 05:23 UTC, fenixD3 commented on srcs/VirtualServer.cpp
> +    m_VS->m_CgiUri = m_LocationBuilder.GetStandardRoutes()[LocationNames::Cgi];
Так он же в итоге построится правильно, зачем тут так хардкодить?

2022-05-27 05:23 UTC, fenixD3 commented on srcs/VirtualServer.cpp
> +    m_VS->m_CgiUri = m_LocationBuilder.GetStandardRoutes()[LocationNames::Cgi];
Так он же в итоге построится правильно, зачем тут так хардкодить?

2022-05-27 16:40 UTC, sdshorin commented on srcs/VirtualServer.cpp
> +    m_VS->m_CgiUri = m_LocationBuilder.GetStandardRoutes()[LocationNames::Cgi];
Есть путь до директории с cgi скриптом - /cgi/
Есть путь, где расположена эта директория - ./root/cgi/
когда к нам приходит запрос вида /cgi/echo.cgi/a/b?x=d, нам нужно понять что это запрос к cgi. Для этого нужен чистый путь до cgi, без ./root/

2022-05-27 16:43 UTC, sdshorin commented on srcs/CgiWorker.cpp
> +	return ReadFile("./tmp/webserv_cgi");
Это временный файл, в который мы пишем и из которого читаем. Раньше было сделано через pipe, но он не заработал, и я в качестве временного решения сделал так. В будущем вынесу в конфиг как temp-директорию, или попробую разобраться с чтением из pipe

2022-05-27 17:20 UTC, fenixD3 commented on srcs/VirtualServer.cpp
> +    m_VS->m_CgiUri = m_LocationBuilder.GetStandardRoutes()[LocationNames::Cgi];
Так а разве мы не поймем из строчки в запросе, что это cgi? По факту полный же путь все равно будет нужен потом.

Или ты имеешь в виду, что нужно сопоставить path из блока location с тем, что пришло в запросе? Если да, то получается, что нам не нужно заранее делать Build для всех путей?

2022-05-28 09:46 UTC, sdshorin commented on srcs/VirtualServer.cpp
> +    m_VS->m_CgiUri = m_LocationBuilder.GetStandardRoutes()[LocationNames::Cgi];
Не поймём. Можно просто конфиг переделать, чтобы в нем было два поля - cgi_scripts_dir и cgi_request pattern

2022-05-28 12:40 UTC, TebaHa approved these changes

2022-05-28 13:00 UTC, fenixD3 commented on srcs/VirtualServer.cpp
> +    m_VS->m_CgiUri = m_LocationBuilder.GetStandardRoutes()[LocationNames::Cgi];
Как вариант. Еще какие-то есть подобные поля?

2022-05-28 18:03 UTC, fenixD3 approved these changes

2022-06-07 21:18 UTC, fenixD3 requested changes

2022-06-07 21:18 UTC, leeroy-Jk commented on srcs/PhysicalServer.cpp
> +	 	if (request->at("Host").rfind(it->second, 0) == 0) {
Погоди, ты тут в rfind передаешь raii_ptr?

2022-06-23 14:51 UTC, fenixD3 approved these changes

2022-06-23 15:21 UTC, merged