Fix post
fenixD3/WebServ pull request #15
Opened 2022-05-29 21:18 UTC by TebaHa

2022-05-30 08:06 UTC, fenixD3 requested changes

2022-05-30 08:06 UTC, leeroy-Jk commented on srcs/IOSocket.cpp
> +		std::cerr << "Bad request" << std::endl;
Разве нам не надо все равно вычитать тело запроса из буфера строки, даже если он не валиден? Иначе же останется возможно часть прошлого запроса при чтении нового

2022-05-30 08:06 UTC, fenixD3 commented on CMakeLists.txt
> -add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD COMMAND cp ${PROJECT_BINARY_DIR}/${PROJECT_NAME} ${PROJECT_SOURCE_DIR}/${PROJECT_NAME})
Оставь плз эту команду, только cp на mv замени

2022-05-30 08:11 UTC, TebaHa commented on CMakeLists.txt
> -add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD COMMAND cp ${PROJECT_BINARY_DIR}/${PROJECT_NAME} ${PROJECT_SOURCE_DIR}/${PROJECT_NAME})
Хорошо.

2022-05-30 16:32 UTC, TebaHa commented on srcs/IOSocket.cpp
> +		std::cerr << "Bad request" << std::endl;
А мы где то дальше по IsValid отправляем ошибки? Можно либо тут читать все подряд и дальше дропать, что как мне кажется лишняя нагрузка. Можно дропать остатки которые дошли.

2022-05-30 19:59 UTC, fenixD3 requested changes

2022-05-30 19:59 UTC, fenixD3 commented on srcs/IOSocket.cpp
> +		std::cerr << "Bad request" << std::endl;
Да в любом случае надо из recv_buf вычитать/удалить тело. Нам может за один раз прийти конец body одного запроса и начало другого

2022-05-30 20:00 UTC, fenixD3 commented on srcs/IOSocket.cpp
> +		std::cerr << "Bad request" << std::endl;
Да в любом случае надо из recv_buf вычитать/удалить тело. Нам может из recv прийти за раз тело одного запроса и начало другого

2022-05-30 20:37 UTC, TebaHa commented on srcs/IOSocket.cpp
> +		std::cerr << "Bad request" << std::endl;
Нужно считать даже если http_req == nullptr? Или только если IsValid() вернет false?

2022-05-30 20:38 UTC, TebaHa commented on CMakeLists.txt
> -add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD COMMAND cp ${PROJECT_BINARY_DIR}/${PROJECT_NAME} ${PROJECT_SOURCE_DIR}/${PROJECT_NAME})
Поправил.

2022-05-30 20:51 UTC, fenixD3 commented on srcs/IOSocket.cpp
> +		std::cerr << "Bad request" << std::endl;
Там не должно быть ситуаций, когда http_req == nullptr

2022-05-30 21:00 UTC, TebaHa commented on srcs/IOSocket.cpp
> +		std::cerr << "Bad request" << std::endl;
Есть. Как раз в телеге разбирали этот случай.

2022-05-30 21:00 UTC, TebaHa commented on srcs/IOSocket.cpp
> +		std::cerr << "Bad request" << std::endl;
Просто как раз тут оно и падает.

2022-05-30 21:02 UTC, sdshorin requested changes
Нужно читать длину из заголовков и считывать весь файл

2022-06-07 13:03 UTC, fenixD3 approved these changes

2022-06-07 20:25 UTC, sdshorin approved these changes

2022-06-07 20:25 UTC, merged