Logger
fenixD3/WebServ pull request #3
Opened 2022-04-09 15:07 UTC by splinehip

Добавил логер. Пишет в stdout/stderr и в фаил.
Logger log;
log.write(level from enum, fmt_msg, ...);

2022-04-10 08:17 UTC, fenixD3 commented on includes/Logger.hpp
> +	DEBUG,
```suggestion
	DEBUG,
	LEVELS_COUNT
```

2022-04-10 08:19 UTC, fenixD3 commented on includes/Logger.hpp
> +	DEBUG,
Давай от макроса избавимся, а количество уровней логирования вот так определять (очень распространенный метод

```suggestion
	DEBUG,
	LEVELS_CNT
```

2022-04-10 08:22 UTC, fenixD3 commented
А зачем ты удалил main, server файлы?

2022-04-10 09:46 UTC, splinehip commented
> 
Думал так будет проще сливать )) Уже рахобрались.

2022-04-11 20:05 UTC, fenixD3 requested changes

2022-04-11 20:05 UTC, leeroy-Jk commented on includes/Logger.hpp
> +	DEBUG,
Давай от макроса избавимся, а количество уровней логирования вот так определять (очень распространенный метод

```suggestion
	DEBUG,
	LEVELS_CNT
```

2022-04-11 20:05 UTC, leeroy-Jk commented on includes/Logger.hpp
> +#ifndef LOGGER_H
`Компиляторами, содержащими ошибки, связанные с #pragma once, являются LCC-Win32 версии 2004 года и GCC версии 1998 года`

Мы собираемся их использовать, чтобы от pragma защищаться?

2022-04-11 20:05 UTC, leeroy-Jk commented on includes/Logger.hpp
> +	Logger(void);
Избыточно его объявление при наличии конструктора с параметрами

2022-04-11 20:05 UTC, leeroy-Jk commented on includes/Logger.hpp
> +	inline int			getLevel(void);
зачем тут и ниже inline?

2022-04-11 20:05 UTC, leeroy-Jk commented on srcs/Logger.cpp
> +static inline std::string	time_stamp(void)
Давайте статические free function вообще не использовать. 

1. При написании тестов их нельзя будет вызвать
2. Если они семантически относятся к логгеру, то очевиднее поместить их в приватные методы
3. Если не относятся напрямую к логированию и могут быть использованы еще где-то (как получение  времени), то логичнее поместить их в отдельный файл utils (под соответствующим namespace) и дергать оттуда

2022-04-11 20:05 UTC, leeroy-Jk commented on srcs/Logger.cpp
> +std::map<std::ofstream*, std::string> stream_file_table;
Глобальные переменные да еще и без namespace - оч опасно. Тем более они относятся к классу логера.

2022-04-11 20:05 UTC, leeroy-Jk commented on srcs/Logger.cpp
> +	if (this->file.is_open() == false)
Предлагаю всегда использовать скобки {}, намного четче видно тело условия, особенно если оно будет на несколько строк

2022-04-11 20:05 UTC, leeroy-Jk commented on srcs/Logger.cpp
> +	*this = inst;
А что будет, если и this, и inst это один и тот же объект? То же и для оператора присваивания

2022-04-11 20:05 UTC, leeroy-Jk commented on srcs/Logger.cpp
> +std::map<std::ofstream*, std::string> stream_file_table;
Почему потоки вообще не удаляются из этой мапы?

2022-04-11 20:05 UTC, leeroy-Jk commented on srcs/Logger.cpp
> +	std::string 		msg;
Лучше использовать std::stringstream (в 98 они есть). Тогда уйдет использование resize отсюда, и не нужен будет глобальный массив levels. А для enum с уровнями логирования просто определить operator<< и передавать во write его

2022-04-11 20:05 UTC, leeroy-Jk commented on includes/Logger.hpp
> +enum e_levels
Для чего дублирование в upper case и lower case?

2022-04-12 08:32 UTC, splinehip commented on includes/Logger.hpp
> +	DEBUG,
Ок

2022-04-12 11:59 UTC, splinehip commented on includes/Logger.hpp
> +#ifndef LOGGER_H
Да вобщем-то нет, но не сложно пару строк добавить.

2022-04-12 11:59 UTC, splinehip commented on includes/Logger.hpp
> +	Logger(void);
Ок

2022-04-12 12:00 UTC, splinehip commented on includes/Logger.hpp
> +	inline int			getLevel(void);
Чтоб заинлайнить функции в местах вызова.

2022-04-12 12:02 UTC, splinehip commented on srcs/Logger.cpp
> +static inline std::string	time_stamp(void)
А из экземпляра приватные методы вызываются? А то к переменным не получить доступ.

2022-04-12 12:03 UTC, splinehip commented on srcs/Logger.cpp
> +	*this = inst;
В присваивание добавил проверку.

2022-04-12 12:06 UTC, splinehip commented on srcs/Logger.cpp
> +	std::string 		msg;
Так vsprintf заполняет массив по переданному указателю, как std::stringstream так передать? И он сам будет размер менять?

2022-04-12 12:07 UTC, splinehip commented on includes/Logger.hpp
> +enum e_levels
Для того что при наборе когда не нажимать шифт ) Убрал.

2022-04-12 15:33 UTC, fenixD3 commented on srcs/Logger.cpp
> +static inline std::string	time_stamp(void)
Все, что в приватной секции видно только внутри класса. Из использующего этот класс кода нельзя

2022-04-12 15:38 UTC, fenixD3 commented on srcs/Logger.cpp
> +	std::string 		msg;
stringstream сам все делает. Просто через << в него все записываем

2022-04-12 16:09 UTC, leeroy-Jk commented on includes/Logger.hpp
> +#ifndef LOGGER_H
Не сложно, но зачем избыточность плодить?

2022-04-12 16:31 UTC, leeroy-Jk requested changes

2022-04-12 16:31 UTC, fenixD3 commented on includes/Logger/loggerUtils.hpp
> +inline std::string	time_stamp(void)
В чем фишка одну функцию в хэдере определить, а другую в cpp?)

2022-04-12 16:31 UTC, fenixD3 commented on includes/Logger.hpp
> +	inline int			getLevel(void);
Если метод опеределен прям в классе, он сразу является кандидатом на встраивание.
Плюс inline это всего лишь пожелание, компилятор его спокойно может и проигноррить

2022-04-12 16:31 UTC, fenixD3 commented on includes/Logger/Logger.hpp
> +
Опять же, в чем логика, часть методов определить здсь, часть вынести в cpp?

2022-04-12 17:44 UTC, splinehip commented on includes/Logger.hpp
> +#ifndef LOGGER_H
Да я бы не сказал, что прям избыточность ))

2022-04-12 17:48 UTC, splinehip commented on includes/Logger.hpp
> +	inline int			getLevel(void);
Я проверял - компилятор инлайнит, а без может быть на стеке вывзовов.

2022-04-12 17:49 UTC, splinehip commented on srcs/Logger.cpp
> +static inline std::string	time_stamp(void)
Поэтому я их частично вынес.

2022-04-12 17:51 UTC, splinehip commented on srcs/Logger.cpp
> +	if (this->file.is_open() == false)
Ну хз, при однострочном ифе это избыточно - отступа более чем достаточно. Но мне не сложно их добавить, так что ок.

2022-04-12 17:51 UTC, splinehip commented on srcs/Logger.cpp
> +	std::string 		msg;
Как ему формат строку и va_arg передать?

2022-04-12 17:53 UTC, splinehip commented on includes/Logger/loggerUtils.hpp
> +inline std::string	time_stamp(void)
Фишка в компиляторе плюсовом - если есть хедер, то компилятор ожидает реализацию инлайновой функции в нем же.

2022-04-12 17:54 UTC, splinehip commented on includes/Logger/Logger.hpp
> +
Тоже самое - компилятор.

2022-04-12 18:43 UTC, fenixD3 requested changes

2022-04-12 18:43 UTC, leeroy-Jk commented on includes/Server.h
> +    Logger             log;
Предполагается, что каждый компонент будет писать лог в свой файл?
Просто, если файл будет один на весь проект, то удобно сделать логер а-ля singleton. Тогда каждый класс не будет владеть логером, а просто ссылаться

2022-04-12 18:43 UTC, leeroy-Jk commented on includes/Logger/Logger.hpp
> +	inline void	setLevel(std::string const &level)
Здесь параметр level скрывает поле level логера. Не самый лучший вариант

2022-04-12 18:43 UTC, leeroy-Jk commented on includes/Logger/Logger.hpp
> +	void		write(int const level, const char *fmt, ...);
То же, что и в setLevel

2022-04-12 18:43 UTC, leeroy-Jk commented on srcs/Server.cpp
> +Server::Server(): log("DEBUG", "webserv.log")
```suggestion
Server::Server()
    : log("DEBUG", "webserv.log")
```

2022-04-12 18:43 UTC, leeroy-Jk commented on srcs/Logger/Logger.cpp
> +	pthread_join(this->pth, NULL);
А не теряется ли смысл асинхронности, когда мы должны дожидаться завершения потока (по сути вычитывания всей очереди логера, блокируя основной поток) при его удалении?

Да и плюс сам поток находится просто в активном ожидании, что вхолостую отжирает ресурсы. Да и логирование не такая уж и частая операция.

И как вариант exit() успевает прибить интсанс логера со всей его внутренней очередью, поэтому и не успевает записать в файл.

2022-04-12 18:43 UTC, leeroy-Jk commented on srcs/Server.cpp
> +        this->log.flush();
Честно, эти две строчки подряд выглядят как дикий костыль

2022-04-12 18:43 UTC, fenixD3 commented on includes/Logger.hpp
> +	inline int			getLevel(void);
А всеми компиляторами проверял ли? И вообще, откуда такая уверенность, что это как-то скажется на оптимизации, замеры какие-то? Преждевременная оптимизация - одна из самых плохих вещей)

А на читаемость и восприятие целостного кода это досаточно сильно влияет, нарушается семантическая целостность объявления-определения и их расположения по файлам. Начинается чехарда: часть функций/методов определена так, часть иначе.

Единственное, когда это оправдано - шаблонные методы, возможно мелкие дружественные функции по типу operator<<

2022-04-12 18:43 UTC, fenixD3 commented on srcs/Logger.cpp
> +	std::string 		msg;
А блин, там же ap этот еще. Хз, я с c-style вариадиками работал только в printf школьном. Если нет способа, то пофиг

2022-04-12 18:43 UTC, fenixD3 commented on srcs/Logger.cpp
> +	if (this->file.is_open() == false)
вот твой кусок кода

	if (this->file.is_open() == false)
		std::cerr << "LGGER: file " << this->file_name << " open error: "
			<< strerror(errno) << std::endl;

У тебя уже один оператор в if разнесен на две строки, т.е. нужно целенаправленно искать ; и относить весть многострочный оператор в нужный блок. Теперь предстаь, что здесь нужно переносить каждый знак << на новую строку - это превращается в еще большую портянку.

Плюс, когда в if составное, сложное условие - каждая его чатсь переносится на новую строку с одним отступом от if. А потом у тебя идет один оператор в этом if и получается надо еще сильнее напрягаться, читая код и ища то место, где заканчивается условие и начинается оператор.

Это на самом деле стандартное требование к code-style во всех компаниях.

2022-04-13 09:22 UTC, splinehip commented on includes/Logger.hpp
> +	inline int			getLevel(void);
Проверял только на гсс. Тут дело не в оптимизации, просто эти функции являются частью одной, вынесены отдельно чтоб не городить простыню.

2022-04-13 09:24 UTC, splinehip commented on includes/Server.h
> +    Logger             log;
Нет, лог фаил один. Посмотрю про сингл.

2022-04-13 09:25 UTC, splinehip commented on includes/Logger/Logger.hpp
> +	inline void	setLevel(std::string const &level)
Не понял, как иначе приватному атрибуту задать значение?

2022-04-13 09:26 UTC, splinehip commented on includes/Logger/Logger.hpp
> +	void		write(int const level, const char *fmt, ...);
Нет, тут левел нужен для указания уровня сообщения, оно в логере будет отфильтровано если логеру задан уровень ниже.

2022-04-13 09:32 UTC, splinehip commented on srcs/Logger/Logger.cpp
> +	pthread_join(this->pth, NULL);
Смысл не теряется - деструктор должен вызываться только при завершении программы. Необходимо дождаться записи всех сообщений на диск.
Логирование может быть достаточно частым - когда идет поток запросов (пару тысяч например) и их обработка нам надо сохранять достаточно заметный объем - запись на диск дорогая операция, эффективнее писать в память а уже логер в отдельном потоке пишет ее на диск. Так вызов логера будет намного меньше блокировать основную программу.
Эксит закрывает дескрипторы, из-за чего поток логера не может корректно завершить запись.

2022-04-13 09:33 UTC, splinehip commented on srcs/Logger/Logger.cpp
> +	pthread_join(this->pth, NULL);
Думаю имеет смысл сделать кастомный эксит_фэил в котором уже ожидать завершения сериализации.

2022-04-13 09:33 UTC, splinehip commented on srcs/Server.cpp
> +        this->log.flush();
Да, согласен. Думаю эксит_фэил сделать.

2022-04-13 11:21 UTC, fenixD3 commented on includes/Logger/Logger.hpp
> +	inline void	setLevel(std::string const &level)
У тебя имена совпадают полностью, я вот о чем

Т.е., если обращаться к членам класса не через this-> то будет плохо в этом случае

2022-04-13 11:31 UTC, fenixD3 commented on includes/Logger.hpp
> +	inline int			getLevel(void);
Как это частью одной, если они вызываются в абсолютно разных частях? flush сейчас в клиенстком коде, setLevel в конструкторе, getLevel в serialize

2022-04-13 12:03 UTC, splinehip commented on includes/Logger.hpp
> +	inline int			getLevel(void);
ну вот там где они вызываются они являются частью. Если я сетлевел закину в прайвет я же не смогу ее потом вызвать?

2022-04-13 12:05 UTC, splinehip commented on includes/Logger/Logger.hpp
> +	inline void	setLevel(std::string const &level)
Не понимаю, это только аргумент функции. Как к атрибуту класса можно обратиться без зис или имени класса\экземпляра?

2022-04-13 13:48 UTC, splinehip commented on srcs/Server.cpp
> +        this->log.flush();
Избавился от костыля. Без кастомного эксита. Похоже, что эксит все таки дергает деструкторы.

2022-04-13 13:53 UTC, splinehip commented on srcs/Server.cpp
> +        this->log.flush();
Поторопился - в стдерр успевает а в фаил нет ))

2022-04-13 15:37 UTC, leeroy-Jk commented on includes/Logger.hpp
> +	inline int			getLevel(void);
Внутри класса можно обращаться ко всем методам и данным этого класса. Private секция для этого и придумана, чтобы оставить внутреннюю реализацию чисто внутри класса. Обращаешься оч просто - просто вызываешь как обычную функцию

Слушай, то, что ты вынес какой-то обособленный кусок кода в отдельную функцию это хорошо, но это не значит что он является частью той функции, где ты его вызываешь, отнюдь. Хотя бы потому, что функция может вызываться впоследствии не только в этом месте одном.

И inline ни коим образом не отражает семантику такой принадлежности, это ключевое слово вообще для другого было придумано.

2022-04-13 15:39 UTC, fenixD3 commented on includes/Logger/Logger.hpp
> +	inline void	setLevel(std::string const &level)
Без this очень просто - берешь и пишешь имя члена класса без this->, все. Посмотри, как это я делаю. Неужели в бассейне этого не было?

2022-04-13 17:58 UTC, splinehip commented on includes/Logger.hpp
> +	inline int			getLevel(void);
Я вынес кусок кода из функции, чтоб она не была простыней, это ее часть. Эти функции не планировал использовать где-то еще.
На сколько я знаю - инлайн это директива компилятора, которая позволяет встроить функцию в тело другой функции и она не будет размещаться на отдельном сегменте стека вызовов. Для этих функций это более чем логично.

2022-04-13 18:19 UTC, splinehip commented on includes/Logger/Logger.hpp
> +	inline void	setLevel(std::string const &level)
Посмотрел, действительно можно, на бассейне не было, но это синтаксический сахар, он туда неявно подставляется. По мне явное всегда лучше неявного, поэтому this-> я бы всегда указывал при обращении к атрибуту экземпляра класса.
В реализации функции, когда необходимо отделить аргумент от атрибута, я аргументу в начале добавляю _

2022-04-13 18:24 UTC, splinehip commented on srcs/Server.cpp
> +        this->log.flush();
Теперь везде успевает без костылей.

2022-04-13 19:53 UTC, splinehip commented
Сделал синглтон, убрал костыль при эксите и активное ожидание, отрефакторил (добавил namespace и объединил функции для сериализации в одну).

2022-04-14 06:57 UTC, fenixD3 requested changes

2022-04-14 06:57 UTC, leeroy-Jk commented on includes/Logger/Logger.hpp
> +enum e_levels
Тогда уж его тоже под namespace. Это же часть логики логера

2022-04-14 06:57 UTC, leeroy-Jk commented on includes/Logger/Logger.hpp
> +		static logger::Log	&inst(void)
Давай функции именовать, начиная с глагола все же. Они же действие отражают

2022-04-14 06:57 UTC, leeroy-Jk commented on srcs/Server.cpp
> +static logger::Log &log = logger::Log::inst();
Т.е. ты сначала (до запуска main) создаешь пустой логер, а потом обязан руками вызвать второй метод для его инициализации. Это же слишком неочевидно, странно и опасно. Хватит одного обращения к нему до вызова inst с параметрами, чтобы все упало

2022-04-14 06:57 UTC, leeroy-Jk commented on srcs/Server.cpp
> +            log.write(INFO, "New connection from %s with socket %i remote\
Зачем такие переносы, плохо читаемые? До лимита символов еще место есть (в 100 уж точно влезет)

2022-04-14 06:57 UTC, leeroy-Jk commented on srcs/Server.cpp
> +                    readable_socket);
Если такой перенос делать, тогда уж начинать с новой строки каждый аргумент

2022-04-14 06:57 UTC, leeroy-Jk commented on includes/Logger/Logger.hpp
> +	inline void	setLevel(std::string const &level)
Это не вопрос явного-неявного, а code-style и раздувания кода + использования неявнго указателя там, где он вообще не нужен и никаких плюсов не несет. Наименовать любые переменные, используя '_' плохо: этот знак плохо видно в таком ключе, его неудобно набирать, такой нейминг используется в кишках стандартных библиотек

2022-04-14 06:57 UTC, leeroy-Jk commented on includes/Logger.hpp
> +	inline int			getLevel(void);
Функции выносятся на основе логической декомпозиции, а не потому что эти строки мешают ей укладываться в число 25-30. Это бред абсолютный. Если функция логически целостна и неделима, то пусть она будет все 70-80 строк кода. Нельзя ни одну функцию считать неотъемлимой частью другой, потому что это два разных логических компонента.

inline это оптимизация ради оптимизации. Компилятор умнее программистов, существенного вклада в производительность директива эта не вносит, люди уже замеряли. Любая оптимизация должна подтверждаться цифрами, если она вно не заметна глазу.

И когда функции определены в хэдере, то при их изменении идет перекомпиляция всего, куда этот .h инклюдится

2022-04-14 08:00 UTC, splinehip commented on includes/Logger/Logger.hpp
> +	inline void	setLevel(std::string const &level)
В том кодстайле что ты скинул как раз для таких аргументов предлагают _ только в окончании слова. Указание this это как раз явно указывает, что идет обращение к атрибуту или методу класса.

2022-04-14 08:05 UTC, splinehip commented on srcs/Server.cpp
> +static logger::Log &log = logger::Log::inst();
Это почему? Потому, что статик? Тогда как в плюсах сделать чтоб переменная было в области видимости модуля?
Если никак тогда надо в каждой функции где нужен логер создавать переменную. Ну либо писать полный вызов для получения инстанса.
"Т.е. ты сначала (до запуска main) создаешь пустой логер, а потом обязан руками вызвать второй метод для его инициализации. " Это не понял - инстанс логера создается с мейне, функцией инит. Тут просто получаем сам инстанс.

2022-04-14 08:06 UTC, splinehip commented on srcs/Server.cpp
> +            log.write(INFO, "New connection from %s with socket %i remote\
Осталось от прошлого когда не умешалось.

2022-04-14 08:07 UTC, splinehip commented on srcs/Server.cpp
> +                    readable_socket);
тоже самое - с прошлого осталось

2022-05-21 07:42 UTC, closed without merging