init server worker
fenixD3/WebServ pull request #7
Opened 2022-05-02 21:58 UTC by sdshorin

2022-05-03 19:57 UTC, fenixD3 commented on srcs/PhysicalServer.cpp
> +			current_msg.msg += recv_buffer.substr(0, end_pos + EndPattern.size()); // А если в этот момент end_pos == npos?
Думал, что все будет ок, но нет. Надо тут исправлять как минимум тернарником

2022-05-04 16:24 UTC, sdshorin commented on srcs/PhysicalServer.cpp
> +			current_msg.msg += recv_buffer.substr(0, end_pos + EndPattern.size()); // А если в этот момент end_pos == npos?
Давай в отдельной, я потом rebase сделаю из мастера

2022-05-15 10:25 UTC, fenixD3 requested changes

2022-05-15 10:25 UTC, leeroy-Jk commented on srcs/VirtualServer.cpp
> +	return std::find(allowed_methods.begin(), allowed_methods.end(), method) != allowed_methods.end();
Этот метод по идее редко должен использоваться?

2022-05-15 10:25 UTC, leeroy-Jk commented on srcs/PhysicalServer.cpp
> +			current_msg.msg += recv_buffer.substr(0, end_pos + EndPattern.size()); // А если в этот момент end_pos == npos?
@sdshorin fix_npos добавил ветку, где пофиксил. Ребейзнешься, можешь удалять ее

2022-05-15 16:52 UTC, sdshorin commented on srcs/VirtualServer.cpp
> +	return std::find(allowed_methods.begin(), allowed_methods.end(), method) != allowed_methods.end();
Один раз для запроса, проверяем, что сервер поддерживает метод

2022-05-19 20:28 UTC, fenixD3 requested changes

2022-05-19 20:28 UTC, leeroy-Jk commented on includes/HttpResponse.h
> +#include "VirtualServer.h"
Случайно добавил или планируешь использовать?

2022-05-19 20:28 UTC, fenixD3 commented on includes/Worker.h
> +class Worker
Не увидел использования

2022-05-20 19:21 UTC, sdshorin commented on includes/HttpResponse.h
> +#include "VirtualServer.h"
Убрал

2022-05-20 19:22 UTC, sdshorin commented on includes/Worker.h
> +class Worker
В этом файле временно хранился класс Location

2022-05-21 19:15 UTC, TebaHa approved these changes

2022-05-21 19:15 UTC, TebaHa approved these changes

2022-05-26 13:23 UTC, TebaHa approved these changes

2022-05-26 14:26 UTC, fenixD3 approved these changes

2022-05-26 14:29 UTC, merged