Добавление билдера реквестов. Он же и обеспечивает парсинг.
fenixD3/WebServ pull request #8
Opened 2022-05-07 19:02 UTC by TebaHa

2022-05-07 19:07 UTC, TebaHa commented
Не сделал язык и CGI. Могу добавить завтра уже.

2022-05-08 12:26 UTC, sdshorin approved these changes

2022-05-09 19:08 UTC, fenixD3 requested changes

2022-05-09 19:08 UTC, leeroy-Jk commented on srcs/Cluster.cpp
> +		HttpRequestBuilder::http_request req =
Подмержи плз master, в этом месте как раз были изменения, и вся обработка происходит на уровне PhysicalServer. Странно, почему конфликта нет сейчас тут

2022-05-09 19:08 UTC, leeroy-Jk commented on srcs/Cluster.cpp
> +			HttpRequestBuilder::GetInstance().BuildHttpRequest(std::string(rec_buf));
Тут еще штука в том, что этот буфер только заголовки будет содержать. И в зависимости от комбинаций заголовков и их значений: "Content-Length: <val>" или "Transfer-Encoding: chunked", - будет разный алгоритм вычитывания инфы из сокета. На этом уровне надо как-то мне получить знание о том, сколько читать и по какому и паттернов

2022-05-15 14:36 UTC, TebaHa commented on srcs/Cluster.cpp
> +		HttpRequestBuilder::http_request req =
Подмержил. Конфлик был. Поправил.

2022-05-15 14:39 UTC, TebaHa commented on srcs/Cluster.cpp
> +			HttpRequestBuilder::GetInstance().BuildHttpRequest(std::string(rec_buf));
Если этих тегов не будет сделаю флаг валидности реквеста не валидным. Также добавлю геттеры на размер контента и тип Transfer-Encoding.

2022-05-15 14:58 UTC, TebaHa commented on srcs/Cluster.cpp
> +			HttpRequestBuilder::GetInstance().BuildHttpRequest(std::string(rec_buf));
Добавил

2022-05-16 08:21 UTC, fenixD3 requested changes

2022-05-16 08:21 UTC, leeroy-Jk commented on srcs/Cluster.cpp
> +			HttpRequestBuilder::GetInstance().BuildHttpRequest(str_buf);
Да, ок. Только смотри, здесь ты получишь не весь запрос, а только часть в общем случае.

Запрос лежит в `PhysicalServer::ReceivingQueue m_PendingRequests `, поэтому наверно логичнее туда перенести обработку запросов. У каждого сообщения есть поле header_filled есть, если оно true, то можно этот элемент с заголовками забирать для парсинга. Самый старый реквест будет во front() храниться, если он с header_filled = false, то дальше по очереди можно и не итерироваться вообще.

Пока я умею только конец заголовков определять точно, для тела запроса мне как раз нужно от парсера знание о том, сколько символов тела читать.

2022-05-16 08:21 UTC, leeroy-Jk commented on srcs/RequestBuilder.cpp
> +		is_valid = false;
Не, смотри, судя по тому, что я вынес из спецификации протокола, то с Content-Length и Transfer-Encoding там такие комбинации могут быть, но запрос все равно остается валидным:

1. Если нет Transfer-Encoding , то Content-Length должен быть, если тело запроса ненулевое
2. Если нет Transfer-Encoding , но Content-Length отсутствует, то тело запроса нулевое (вроде так, монжно перепроверить, правда ли Content-Length может не быть в этом случае)
3. Если есть Transfer-Encoding: chunked, то на Content-Length вообще пофиг (его и не должно там быть). Тогда там свой паттерн нахождение конца тела '0\r\n\r\n'
4. Для других Transfer-Encoding не нашел инфы

2022-05-18 18:08 UTC, TebaHa commented on srcs/RequestBuilder.cpp
> +		is_valid = false;
Тебе нормально будет смотреть с начало значение m_transfer_encoding_status, а потом если оно невалидное идти смотреть на размер. Content-Length? Или лучше сделать обший энумератор-статус по реквесту?

2022-05-18 18:39 UTC, TebaHa commented on srcs/RequestBuilder.cpp
> +		is_valid = false;
Вообщем сделал статус по энумератору Transfer-Encoding. Добавил у него еще одно значение - STATIC. Это значит, что размер тела идет через Content-Length. Ну и геттеры поменял.

2022-05-18 18:39 UTC, TebaHa commented
Добавил CGI.

2022-05-18 18:40 UTC, TebaHa commented on srcs/Cluster.cpp
> +			HttpRequestBuilder::GetInstance().BuildHttpRequest(str_buf);
Перенес и разделил билдинг реквеста на два метода. Один собственно считывает хедер. Другой - body.

2022-05-18 19:44 UTC, fenixD3 approved these changes

2022-05-18 19:45 UTC, merged